services:
  new-mitigations:
    build: .
    ports:
      - 6342:5000
    cap_drop:
      - all
    cap_add:
      - chown
      - setuid
      - setgid
      - sys_admin
      - mknod
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
      - systempaths=unconfined
